### ISSUE TITLE
Stuttering issue

### ISSUE THREAD

**Issue by demib84** [AndyMt/GravityTurn#29]
Hello,

After installing this mod, I have been getting stuttering during launches. It is worse when I have auto stage disabled, but it does happen a bit even with it. I removed the mod and the stuttering disappeared. I am no expert, but perhaps it has something to do with the VRAM. There is a noise I do believe is from the GPU and it fades in and out along with the stutters. I did not even notice it before until now. haha 

This is a log where I did a launch with GT
[output_log4.txt](https://github.com/AndyMt/GravityTurn/files/578143/output_log4.txt)

This is a log of the same, but without GT installed
[output_log5.txt](https://github.com/AndyMt/GravityTurn/files/578145/output_log5.txt)

Thank you for your time.

**Comment by AndyMt** [comment]
I think I know what causes the worsened issue when having auto staging off now. I'm still not sure about the general stutter you describe.

**Comment by AndyMt** [comment]
Found the cause. Stutter will be gone.

**Comment by demib84** [comment]
Awesome, thank you.
